/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gtst_gittest;

public class App {
    public static void main(String[] args) {
        System.out.println("This is a good test")
    }
}
